#!/bin/sh
### BEGIN INIT INFO
# Provides:          letsencrypt
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       "init letsencrypt"
### END INIT INFO


SCRIPT=/usr/local/sbin/scw-letsencrypt
RUNAS=root

PIDFILE=/var/run/letsencrypt.pid
LOGFILE=/var/log/letsencrypt.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service...' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

case "$1" in
  start)
    start
    ;;
  *)
    echo "Usage: $0 {start}"
esac
